### PR TITLE
fix: Fix Orama search not working on /docs

### LINKED ISSUE #348: Website search function doesn't return any results
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Plugin version

1.x.x

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

x

### Description

Image

The website currently uses orama for search, and this doesn't return results for any query, even things that obviously are on the website, like 'Fastify', 'GET', or 'TypeScript

### Link to code that reproduces the bug

https://fastify.dev/docs/latest/Guides/

### Expected Behavior

The website search function should return results

### PR DESCRIPTION
**Pull request by smith558**
## Description

  - **Issue**: Orama search returned no results on `/docs` because the Orama Docusaurus plugin passed the Docusaurus v3 version object straight into `searchParams.where.version`, which expects a string, so the filter never matched.
  - **Cause**: a bug in `@orama/plugin-docusaurus-v3`, it assumes `useVersions()` returns a string; Docusaurus v3 returns version objects.
  - **Fix**: Applied a small `patch-package` diff to coerce the version object to its `.name` (with sensible fallbacks) before building the search filter. Added `patch-package` + `postinstall` to keep the patch applied, documented it in `patches/README.md`, and removed the previous local SearchBar swizzle (initial fix version).

  ### Notes
image

  ## Related Issues

  #348
  https://github.com/fastify/fastify/issues/6390

  ## Check List

  - [x] I have read the Contributing Guidelines (./CONTRIBUTING.md)

### CODE REVIEW

**Comment by smith558** [comment]
I don't understand why the CI/CD fails. It works locally.

```js
Error:  Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/runner/work/website/website/node_modules/@docusaurus/core/lib/commands/build/build.js:83:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /home/runner/work/website/website/node_modules/@docusaurus/core/lib/commands/build/build.js:35:9
    at async mapAsyncSequential (/home/runner/work/website/website/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/home/runner/work/website/website/node_modules/@docusaurus/core/lib/commands/build/build.js:34:5)
    at async Promise.all (index 0)
    at async runCLI (/home/runner/work/website/website/node_modules/@docusaurus/core/lib/commands/cli.js:56:5)
    at async file:///home/runner/work/website/website/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Failed to compile due to Webpack errors.
  Module not found: Error: Can't resolve '@orama/react-components' in '/home/runner/work/website/website/src/theme/SearchBar'
      at /home/runner/work/website/website/node_modules/@docusaurus/bundler/lib/compiler.js:49:24
      at /home/runner/work/website/website/node_modules/webpack/lib/MultiCompiler.js:629:14
      at processQueueWorker (/home/runner/work/website/website/node_modules/webpack/lib/MultiCompiler.js:566:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
}
[INFO] Docusaurus version: 3.9.2
Node version: v22.21.1
Error: Process completed with exit code 1.
```

File: src/theme/SearchBar/index.js [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+import { useLocation } from '@docusaurus/router'
+import BrowserOnly from '@docusaurus/BrowserOnly'
+import { useActiveVersion, useVersions } from '@docusaurus/plugin-content-docs/client'
+import { usePluginData } from '@docusaurus/useGlobalData'
+
+// Reuse Orama's theme helpers but ensure the search filter receives a version name string.
+import useOrama from '@orama/plugin-docusaurus-v3/dist/theme/SearchBar/useOrama.js'
+import { getColorMode, getPreferredVersion } from '@orama/plugin-docusaurus-v3/dist/theme/SearchBar/utils.js'
+
+const oramaComponentsPath = '../../node_modules/@orama/react-components/dist/index.js'
```
Comment (Eomm) [inline src/theme/SearchBar/index.js]: Why we can't `import @orama/react-components`?

Right now the page does not work:

Image

**Review by Eomm — COMMENTED** [review]
Do we know the offending issue?
Why do we need a wrapper now?

File: src/theme/SearchBar/index.js (hunk 1 above)
Comment (smith558) [reply src/theme/SearchBar/index.js]: Yes, that's something I do not understand. It builds and works locally for me just fine. But crashes on GH CI/CD if `import @orama/react-components` used. I was hoping you'd know how to resolve this.

Comment (Eomm) [reply src/theme/SearchBar/index.js]: Does
`import { OramaSearchButton, OramaSearchBox } from '@orama/react-components'`

work?

**Comment by smith558** [comment]
> Do we know the offending issue? Why do we need a wrapper now?

The issue is that the Orama plugin assumes `useVersions()` (from `@docusaurus/plugin-content-docs/client`) returns a string, but in Docusaurus v3, it returns version objects. It forwards that object into `searchParams.where.version` (in `OramaSearchBox`), and therefore the query never matches. This is an Orama bug.

**Comment by smith558** [comment]
@Eomm I've reworked this. This fix is much better now. Tested locally as much as possible.

File: patches/@orama+plugin-docusaurus-v3+3.1.16.patch [hunk 2]
```diff
@@ -0,0 +1,31 @@
+diff --git a/node_modules/@orama/plugin-docusaurus-v3/dist/theme/SearchBar/index.js b/node_modules/@orama/plugin-docusaurus-v3/dist/theme/SearchBar/index.js
+index eab29fc..2555aa0 100644
+--- a/node_modules/@orama/plugin-docusaurus-v3/dist/theme/SearchBar/index.js
++++ b/node_modules/@orama/plugin-docusaurus-v3/dist/theme/SearchBar/index.js
```
Comment (Eomm) [inline patches/@orama+plugin-docusaurus-v3+3.1.16.patch]: We should open a PR on their repo instead:
https://github.com/oramasearch/orama/tree/main/packages/plugin-docusaurus-v3

**Comment by Eomm** [comment]
> @Eomm I've reworked this. This fix is much better now. Tested locally as much as possible.

Yeah, it looks much better, but if the issue is not in this repo, we should fix this issue for everyone. WDYT?

**Comment by smith558** [comment]
> > @Eomm I've reworked this. This fix is much better now. Tested locally as much as possible.
> 
> Yeah, it looks much better, but if the issue is not in this repo, we should fix this issue for everyone. WDYT?

Yes, I am working on a PR for the upstream as well. However, with the holidays coming, I don't think it will be sooner than a month from now before it gets merged (I am off for 3 weeks starting tomorrow + Orama PR review).

Why not patch it first? I'd put search not working on the docs for at least 3 months as high impact. I am happy to remove the patch later with a PR.

File: patches/@orama+plugin-docusaurus-v3+3.1.16.patch (hunk 2 above)
Comment (ilteoood) [reply patches/@orama+plugin-docusaurus-v3+3.1.16.patch]: Totally agree with this.
I'll open a PR to Orama to make it happen.

**Comment by ilteoood** [comment]
I'll talk to the Orama team to address it ASAP.
A PR with your patch has been opened [here](https://github.com/oramasearch/orama/pull/1005/files)

**Comment by smith558** [comment]
I just saw you got it merged. @ilteoood

**Comment by ilteoood** [comment]
You can keep this PR open IMHO, @smith558 
We still need to upgrade the lib once it gets released.
Additionally, do we still need to update docuraurus' config to `lastVersion: 'latest', // the last version is always "latest"`?

**Comment by smith558** [comment]
To be completely frank. I do feel a bit uncomfortable about how this played out.

I spent quite a lot of time debugging this and identifying the root cause, and I was in the process of opening a PR to `oramasearch/orama`. I was just waiting for guidance from @Eomm on the best way to proceed.

This was shaping up to be my first meaningful contribution either to Fastify or Orama, so seeing the same fix copied 1:1 and merged upstream was a bit disappointing.

I’m genuinely glad the issue is fixed for everyone. I just wanted to share how this landed from my side.

**Comment by ilteoood** [comment]
I'm sorry about this, but considered your concerns about the time needed for the upstream merge + the fact that you will be on holiday for three weeks, made me realize that probably things needed to be pushed a bit in order to be smoother.
You have also been credited in the PR that has been opened: I've both tagged you and referenced this discussion for historical reasons so...to me, it has been your first meaningful contribution to both the projects.

**Comment by smith558** [comment]
for lib upgrade

**Comment by Eomm** [comment]
Nice job @smith558 - Could you cleanup this PR to update the orama plugin required version?

**Comment by smith558** [comment]
this is ready now

**Review by ilteoood — APPROVED** [review]

**Comment by ilteoood** [comment]
Thank you so much for your contribution, @smith558
